const wordsEB = {
  name: "OptyDoc",

  //topBar
  topBarAddBlock: "Add block",
  topBarRemoveBlock: "RemoveBlock",
  topBarCopyBlock: "Copy block",
  topBarPasteInside: "Paste inside",
  topBarPasteBefore: "Paste before selected",
  topBarImportTemplate: "Import template",
  topBarExportTemplate: "Export template",
  topBarNewTemplate: "New template",
  topBarChangeTheme: "Change color mode",
  topBarChangeLanguage: "Change language",
  //sideBar
  sideBarEdit: "Edit",
  sideBarCopy: "Copy",
  //ui
  uiConfirmNewTemplateHeader: "Confirm action",
  uiConfirmNewTemplateText: "Are you sure you want to overwrite current template",
  uiPasteHeader: "Paste block text here",
  uiPasteText: "Sorry there is no better way to do it for now",
  //toasts
  uiNewTemplateCreated: "New template created",
  uiNoBlockSelected: "No block selected",
  uiBlockCopiedToClipboard: "Block copied to clipboard", 
  uiBlockDecodingProblem: "Block decoding problem",
  uiOk: "Ok",
  uiCancel: "Cancel",
  uiConfirm: "Confirm",
  uiProseed: "Proseed",

  //mi
  miPageSize: "Page size",
  A4: "A4",
  A5: "A5",
  A3: "A3",
  miPageOrientation: "Page orientation",
  horizontal: "Horizontal",
  vertical: "Vertical",
  miPadding: "Margins",
  miLastChangeTime: "Last change",
  miName: "Name",
  miContent: "Content",
  miDisplay: "Display",
  miDisplayInline: "Inline",
  miDisplayBlock: "Block",
  miDisplayFlex: "Flex",
  miDisplayNone: "None",
  miInherit: "Inherit",
  miWidth: "Width",
  miHeight: "Height",
  miFlexAlignHorizontal: "Flex align horizontal",
  miFlexAlignVertical: "Flex align vertical",
  miAlignTop: "Top",
  miAlignBottom: "Bottom",
  miAlignCenter: "Center",
  miAlignRight: "Right",
  miAlignLeft: "Left",
  miContentType: "Content type",
  miFixed: "Fixed",
  miVariable: "Variable",
  miSelect: "Select",
  miCopyFrom: "CopyFrom",
  miBackground: "Background",
  miEditMiList: "Edit styles list",
  miTextColor: "Text color",
  miFontFamily: "Font",
  miFlexWrap: "Flex wrap",
  miWrap: "Wrap",
  miNoWrap: "No wrap",
  undefined: ""
};

export default wordsEB;