const wordsEB = {
  name: "OptyDoc",

  //topBar
  topBarAddBlock: "Add block",
  topBarRemoveBlock: "RemoveBlock",
  topBarCopyBlock: "Copy block",
  topBarPasteInside: "Paste inside",
  topBarPasteBefore: "Paste before selected",
  topBarImportTemplate: "Import template",
  topBarExportTemplate: "Export template",
  topBarNewTemplate: "New template",
  topBarChangeTheme: "Change color mode",
  topBarChangeLanguage: "Change language",
  topBarCutBlock: "Cut block",
  topBarDuplicateBlock: "Duplicate block",
  topBarPrint: "Print",
  topBarAddCopy: "Add copy",
  topBarRemoveCopy: "Remove copy",
  topBarPreviusCopy: "Previus copy",
  topBarNextCopy: "Next copy",
  topBarImportCSV: "Import CSV file",
  topBarExportCSV: "Export copies as CSV file",
  //sideBar
  sideBarEdit: "Edit",
  sideBarCopy: "Copy",
  //ui
  uiConfirmNewTemplateHeader: "Confirm action",
  uiConfirmNewTemplateText: "Are you sure you want to overwrite current template",
  uiPasteHeader: "Paste block text here",
  uiPasteText: "Sorry there is no better way to do it for now",
  uiOk: "Ok",
  uiCancel: "Cancel",
  uiConfirm: "Confirm",
  uiProseed: "Proseed",
  uiPrinted: "Printed",
  uiTemplateExportred: "Template exported",
  uiTemplateDecodingProblem: "Template decoding error",
  uiTemplateImported: "Template imported",
  uiTemplateImporting: "Template importing...",
  uiTemplateExporting: "Template exporting...",
  uiNone: "None",
  //toasts
  uiNewTemplateCreated: "New template created",
  uiNoBlockSelected: "No block selected",
  uiBlockCopiedToClipboard: "Block copied to clipboard", 
  uiBlockDecodingProblem: "Block decoding problem",
  uiImageHasToBeLessThenMB: "Error: Image has to be less then 3MB",
  uiClickOnBlockToSelectAsReference: "Click on block to select as reference",
  uiDisclamerPrintingHeader: "Information for firefox users",
  uiDisclamerPrintingText: "For better printing experience use Chrome :)\n If no, set page background manualy and zoom to default 100%(ctrl+0)",

  //mi
  miPageSize: "Page size",
  A4: "A4",
  A4Chrome: "A4 for Chrome",
  A4Firefox: "A4 for Firefox",
  A5: "A5",
  A3: "A3",
  miPageOrientation: "Page orientation",
  horizontal: "Horizontal",
  vertical: "Vertical",
  miPadding: "Margins",
  miLastChangeTime: "Last change",
  miName: "Name",
  miContent: "Content",
  miDisplay: "Display",
  miDisplayInline: "Inline",
  miDisplayBlock: "Block",
  miDisplayFlex: "Flex",
  miDisplayNone: "None",
  miInherit: "Inherit",
  miWidth: "Width",
  miHeight: "Height",
  miFlexAlignHorizontal: "Flex align horizontal",
  miFlexAlignVertical: "Flex align vertical",
  miFlexAlignContentVertical: "Flex align content vertical",
  miTop: "Top",
  miBottom: "Bottom",
  miCenter: "Center",
  miRight: "Right",
  miLeft: "Left",
  miSpaceEvenly: "Space evenly",
  miSpaceAround: "Space around",
  miSpaceBetween: "Space between",
  miContentType: "Content type",
  miReferenceId: "Reference Id",
  miVariableLabel: "Variable label",
  miFixed: "Fixed",
  miVariable: "Variable",
  miSelect: "Select",
  miCopyFrom: "CopyFrom",
  miBackgroundColor: "Background color",
  miBackgroundImage: "Background image",
  miBackgroundSize: "Background size",
  miBackgroundRepeat: "Background repeat",
  miBackgroundPosition: "Background position",
  miEditMiList: "Edit styles list",
  miFontFamily: "Font",
  miFontSize: "Font size",
  miFontColor: "Font color",
  miFontWeight: "Font weight",
  miFontStyle: "Font style",
  miFontIndent: "Font indent",
  miFlexWrap: "Flex wrap",
  miWrap: "Wrap",
  miNoWrap: "No wrap",
  miContain: "Contain",
  miCover: "Cover",
  miNoRepeat: "No repeat",
  miRepeat: "Repeat",
  miBorder: "Border",
  miBorderTop: "Border top",
  miBorderBottom: "Border bottom",
  miBorderRight: "Border right",
  miBorderLeft: "Border left",
  miMargin: "Margin",
  miSerif: "Serif",
  miSansSerif: "SansSerif",
  miMonospace: "Monospace",
  miNormal: "Normal",
  miBold: "Bold",
  miItalic: "Italic",
  undefined: ""
};

export default wordsEB;