import { WordType } from "../store/translation";

const wordsUA: Record<WordType, string> = {
  name: "OptyDoc",

  //topBar
  topBarAddBlock: "Dodaty blok",
  topBarRemoveBlock: "Vydalyty blok",
  topBarCopyBlock: "Kopiyuvaty",
  topBarPasteInside: "Vstavity vseredinu",
  topBarPasteBefore: "Vstavity pered vydilenym",
  topBarImportTemplate: "Importuvaty maket",
  topBarExportTemplate: "Eksportuvaty maket",
  topBarNewTemplate: "Novy maket",
  topBarChangeTheme: "Zminyty temu",
  topBarChangeLanguage: "Zminyty movu",
  topBarCutBlock: "Virevaty blok",
  topBarDuplicateBlock: "Dublyuvaty blok",
  topBarPrint: "Print",
  //sideBar
  sideBarEdit: "Макет",
  sideBarCopy: "Копії",

  //ui
  //confirms, prompts
  uiConfirmNewTemplateHeader: "Підтрердіть дію",
  uiConfirmNewTemplateText: "Впевнені що хочете перезаписати цей макет?",
  uiPasteHeader: "Vsavte tekst sudy",
  uiPasteText: "No znaishov krashogo vohodu",
  uiOk: "Ок",
  uiCancel: "Відминити",
  uiConfirm: "Підтвердити",
  uiProseed: "Продовжити",
  //toasts
  uiNewTemplateCreated: "Новий мекет створено",
  uiNoBlockSelected: "Niyakogo bloku ne vidileno",
  uiBlockCopiedToClipboard: "Blok skopiyovano", 
  uiBlockDecodingProblem: "Pomilka shifruvaniya bloku",
  uiImageHasToBeLessThenMB: "Error: Image has to be less then 3MB",

  //mi
  miPageSize: "Розмір аркуша",
  A4: "A4",
  A5: "A5",
  A3: "A3",
  miPageOrientation: "Орієнтація сторінки",
  horizontal: "Горизонтально",
  vertical: "Вертикально",
  miPadding: "Відступи",
  miLastChangeTime: "Час останьої зміни",
  miName: "Назва",
  miContent: "Kontent",
  miDisplay: "Vidobrajannya",
  miDisplayInline: "Strokoy",
  miDisplayBlock: "Blokom",
  miDisplayFlex: "Fleks",
  miDisplayNone: "Pryhovano",
  miInherit: "Nasliduye",
  miWidth: "Shirota",
  miHeight: "Vysota",
  miFlexAlignHorizontal: "Fleks align horizontal",
  miFlexAlignVertical: "Fleks align vertical",
  miTop: "Zverhu",
  miBottom: "Znizu",
  miCenter: "Po centru",
  miRight: "Zprava",
  miLeft: "Zliva",
  miContentType: "Tip kontentu",
  miFixed: "Statychny",
  miVariable: "Zminna",
  miSelect: "Vibir",
  miCopyFrom: "Kopiyuvaty z",
  miBackgroundColor: "Kolir fonu",
  miBackgroundImage: "Zobrazhennya fonu",
  miBackgroundSize: "Rozmir fonu",
  miBackgroundRepeat: "Povtorennya fonu",
  miBackgroundPosition: "Polozhennya fonu",
  miEditMiList: "Zminyty spisok styliv",
  miFontFamily: "Shrift",
  miFontColor: "Kolir shrifta",
  miFontSize: "Rozmir shrifta",
  miFlexWrap: "Fleks perenos blokov",
  miWrap: "Perenosit'",
  miNoWrap: "Ne perenosit'",
  undefined: ""
};

export default wordsUA;