import { WordType } from "../store/translation";

const wordsUA: Record<WordType, string> = {
  name: "ОптіДок",

  //topBar
  topBarAddBlock: "Додати блок",
  topBarRemoveBlock: "Видалити блок",
  topBarCopyBlock: "Копіювати",
  topBarPasteInside: "Вставити",
  topBarPasteBefore: "Вставити попереду",
  topBarImportTemplate: "Імпортувати макет",
  topBarExportTemplate: "Експортувати макет",
  topBarNewTemplate: "Новий макет",
  topBarChangeTheme: "Змінити тему",
  topBarChangeLanguage: "Змінити мову",
  topBarCutBlock: "Вирізати блок",
  topBarDuplicateBlock: "Дублювати блок",
  topBarPrint: "Друкувати",
  //sideBar
  sideBarEdit: "Макет",
  sideBarCopy: "Копії",

  //ui
  //confirms, prompts
  uiConfirmNewTemplateHeader: "Підтрердіть дію",
  uiConfirmNewTemplateText: "Впевнені що хочете перезаписати цей макет?",
  uiPasteHeader: "Вставте текст сюди",
  uiPasteText: "Не знайшов надійнішого шляху",
  uiOk: "Ок",
  uiCancel: "Відминити",
  uiConfirm: "Підтвердити",
  uiProseed: "Продовжити",
  uiPrinted: "Nadrukovano",
  uiTemplateExportred: "Maket eksportovano",
  uiTemplateDecodingProblem: "Pomylka shyfruvannya maketu",
  uiTemplateImported: "Maket importovano",
  uiTemplateImporting: "Importuvannya maketu...",
  uiTemplateExporting: "Eksportuvannya maketu...",
  //toasts
  uiNewTemplateCreated: "Новий мaкет створено",
  uiNoBlockSelected: "Жодного блоку не виділено",
  uiBlockCopiedToClipboard: "Блок скопійовано", 
  uiBlockDecodingProblem: "Помилка шифрування",
  uiImageHasToBeLessThenMB: "Помилка: Зображення має бути розміром менше 3МБ",

  //mi
  miPageSize: "Розмір аркуша",
  A4: "A4",
  A4Chrome: "A4 для Chrome",
  A4Firefox: "A4 для Firefox",
  A5: "A5",
  A3: "A3",
  miPageOrientation: "Орієнтація сторінки",
  horizontal: "Горизонтально",
  vertical: "Вертикально",
  miPadding: "Відступи",
  miLastChangeTime: "Час останьої зміни",
  miName: "Назва",
  miContent: "Контент",
  miDisplay: "Відображення",
  miDisplayInline: "Стокою",
  miDisplayBlock: "Блоком",
  miDisplayFlex: "Флекс блоком",
  miDisplayNone: "Приховати",
  miInherit: "Наслідує",
  miWidth: "Широта",
  miHeight: "Висота",
  miFlexAlignHorizontal: "Флекс горизонтальне рівняння",
  miFlexAlignVertical: "Флекс вертикальне рівняння",
  miTop: "Зверху",
  miBottom: "Знизу",
  miCenter: "Поцентру",
  miRight: "Зправа",
  miLeft: "Зліва",
  miContentType: "Тип контенту",
  miFixed: "Статичний",
  miVariable: "Змінна",
  miSelect: "Вибір",
  miCopyFrom: "Копіювати з",
  miBackgroundColor: "Колір фону",
  miBackgroundImage: "Зображення фону",
  miBackgroundSize: "Розмір фону",
  miBackgroundRepeat: "Повторення фону",
  miBackgroundPosition: "Положення фону",
  miEditMiList: "Змінити список стилів",
  miFontFamily: "Шрифт",
  miFontColor: "Колір фришту",
  miFontSize: "Розмір фрифту",
  miFlexWrap: "Флекс перенос блоків",
  miWrap: "Переносити",
  miNoWrap: "Не переносити",
  miContain: "По меншій стороні",
  miCover: "По більшій стороні",
  miNoRepeat: "Не повторювати",
  miRepeat: "Повторювати",
  undefined: ""
};

export default wordsUA;